route:
  receiver: 'discord'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  routes:
    - match: 
        severity: critical
      receiver: 'discord'
    - match:
        severity: warning
      receiver: 'discord'

receivers:
  - name: 'discord'
    discord_configs:
      - webhook_url_file: '/tmp/discord_webhook'
        title: '{{ .Status | toUpper }} - {{ .GroupLabels.alertname }}'
        message: '{{ range .Alerts }}{{ .Annotations.summary }}: {{ .Annotations.description }}{{ end }}'
