global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    origin_prometheus: 'url-shortener-prod'

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#             - "alertmanager:9093"

rule_files:
  - /etc/prometheus/prometheus-rules.yml

scrape_configs:
  - job_name: "flask-app"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["web:8000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # - job_name: "cadvisor"
  #   static_configs:
  #     - targets: ["cadvisor:8080"]

remote_write:
  - url: https://prometheus-prod-32-prod-ca-east-0.grafana.net/api/prom/push
    basic_auth:
      username: "3106840"
      password_file: /run/secrets/grafana_cloud_token
